### ISSUE TITLE
Need you help to make external cheat

### ISSUE THREAD

**Issue by SaSukiTB** [shmoo419/CriticalOpsAimbot#2]
.

**Comment by shmoo419** [comment]
What is your budget?

**Comment by SaSukiTB** [comment]
> What is your budget?

We can pay as much as you want bro, send me your discord or telegram and lets talk, btw you already worked on the game before and it should be easy for you to do it.

**Comment by shmoo419** [comment]
Sure. My Discord is: shmoo419#3112

**Comment by SaSukiTB** [comment]
Hi bro, i hope you're well
We still waiting you
